name: pkcs7
description: |
  Pkcs7 message parser and verification library
  Can parse and generate x509 certificates, request Timestamp, build and
  verify an s-mime PKCS #7 message.
version: 1.0.5
homepage: https://github.com/DavBfr/dart_pkcs7
repository: https://github.com/DavBfr/dart_pkcs7
issue_tracker: https://github.com/DavBfr/dart_pkcs7/issues
funding:
  - https://buymeacoffee.com/JORBmbw9h
topics:
  - crypto
  - security

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  pem: ^2.0.0
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.22.2
